#pragma once

#include "amoeba/context/context_package.hpp"

#include <cstddef>
#include <optional>
#include <string>

namespace amoeba::reasoning {

/**
 * @brief Represents a request payload dispatched to the LLM reasoning runtime.
 *
 * It contains the user's question, the deterministic bounded ContextPackage
 * produced by the Amoeba retrieval and evidence pipeline, and optional inference options.
 */
struct LLMRequest {
    /// The user question or code inquiry.
    std::string user_question;

    /// The bounded context package containing retrieved evidence and rendered markdown.
    context::ContextPackage context_package;

    /// Optional override for the grounding system prompt.
    std::optional<std::string> system_prompt_override{std::nullopt};

    /// Sampling temperature (default 0.0 for deterministic factual code reasoning).
    double temperature{0.0};

    /// Maximum tokens to generate (optional).
    std::optional<std::size_t> max_tokens{std::nullopt};

    bool operator==(const LLMRequest& other) const = default;
};

/**
 * @brief Represents a complete response generated by the LLM reasoning runtime.
 */
struct LLMResponse {
    /// The generated text content or final answer.
    std::string content;

    /// The name/identifier of the model that produced this response.
    std::string model_name;

    /// Whether the generation succeeded without runtime errors.
    bool success{true};

    /// Detailed error message if success is false.
    std::string error_message;

    /// Finish reason reported by the model (e.g., "stop", "length", "error").
    std::string finish_reason{"stop"};

    [[nodiscard]] bool ok() const noexcept { return success && error_message.empty(); }

    bool operator==(const LLMResponse& other) const = default;
};

}  // namespace amoeba::reasoning
